### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rwatts3** [Akryum/vue-meteor#106]
Hello @Akryum ,

First and foremost I like the work you've done to help move Vuejs into the Meteor community.
I have used a few different approaches in your documentation.
I would like to ask some guidance and possibly get your input.
I currently maintain and run the Scorpiusjs project, and the original interface greatly used iron router and kadira flow router projects within it's core.

At this point I want to completely move to the Vue side of things, but finding it quite difficult to get vue router to place nicely side by side with iron router until I can incrementally get things up to date.

Do you have any suggestions or advice on the best approach to do such a thing. 

-v/r

Ryan

**Comment by Akryum** [comment]
Hi! There was some discussion about this [in the forum](https://forums.meteor.com/t/what-a-best-alternative-for-flowrouter-now-after-lost-arunoda-and-kadira/31846/71?u=akryum). Feel free to ask more related questions here.
