### ISSUE TITLE
Connection Failures when not using local machine to connect to Meteor-Vue

### ISSUE THREAD

**Issue by rwuttke** [Akryum/vue-meteor#107]
This is not a BUG.

I am running an instance on Meteor with the meteor-vue components and it is working well. I am developing on Windows with a server running on Linux.

Unfortunately, when I connect to this instance from a the windows machine it is not working correctly.

It does render the basic HTML, no css. The HMR is attempting to connect to localhost:3000, where it is not running.

When I connect from my windows machine to **eniac**, a Ubuntu server, I get the following console error:

`GET http://localhost:3003/socket.io/?EIO=3&transport=polling&t=LdMPEbp&b64=1 net::ERR_CONNECTION_REFUSED`

I looked through the code and noticed it was using Meteor.absolutePath, recently added via a pull request, when creating the socket, and this appears to be the cause.

When run just with the command `meteor`, Meteor.absolutePath always returns localhost:3000, which is as expected.

Using `ROOT_URL=http://eniac:3000 meteor` works as expected.

Can this be added to the documentation, for people working with this kind of configuration?

Meteor Version: 1.4.2.3
Vue Version: 2.1.10
akryum:vue Version: 1.2.2
akryum:vue-component Version: 0.81

**Comment by Akryum** [comment]
Automatic IP detection landed in `vue-component@0.8.16`
