### ISSUE TITLE
Usage within a Meteor Package

### ISSUE THREAD

**Issue by rwatts3** [Akryum/vue-meteor#110]
Greetings,

How would I use your package within a meteor package. I'm creating an admin framework that will be distributed via a Meteor package. and I would like to have the view layer built upon Vue and this package.

How difficult would it be to get this working ? 

Ryan

**Comment by Akryum** [comment]
In your `package.js`, use the `akryum:vue-component`:

```javascript
api.use('akryum:vue-component@0.8.4');
```

Now, all the `.vue` files will work as usual.
