### ISSUE TITLE
getMeteorPort is making the wrong assumption and prevents Meteor to start normally

### ISSUE THREAD

**Issue by sebastianconcept** [Akryum/vue-meteor#112]
Hi Guillaume, 

First of all thanks for your work on this, the stack feels terrific!

As I was working with it, I've found out that you can't use it in a production environment because `.getMeteorPort` tries to infer the port from `ROOT_URL` / `.absoluteUrl()` which they don't have port numbers.

As you can see here, it will have `result` as `null` and length will throw an exception https://github.com/Akryum/meteor-vue-component/blob/master/packages/vue-component-dev-server/server/main.js#L4
<img width="719" alt="universalaccessd universalaccessd today at 6 36 05 pm" src="https://cloud.githubusercontent.com/assets/475508/22621354/cf06bf70-eb08-11e6-95d0-735f99f83b00.png">

If you set this environment variable you can prevent this problem `HMR_PORT=3003`

**Comment by MartinBucko** [comment]
@Akryum I think this is allready fixed [here](https://github.com/Akryum/meteor-vue-component/pull/100/files#diff-26959cdce8f9e9ec2e07c0bac6066129L4)

**Comment by Akryum** [comment]
Could you please try with the latest version?
