### ISSUE TITLE
Meteor.user() undefined when refreshing/first load

### ISSUE THREAD

**Issue by janat08** [Akryum/vue-meteor#118]
Refreshing or landing on page that has Meteor.user() in it will cause errors. Specifically in find({own: Meteor.user()._id}).

**Comment by janat08** [comment]
I did fix that with if statement, but I imagine you could set script tag for meteor above vue.

**Comment by janat08** [comment]
https://github.com/alanning/meteor-roles/issues/218
There's this that deals with Meteor.user() business, and they either use callback or use composer (don't know what that does)

**Comment by janat08** [comment]
also passing Meteor.user() into vue data appears to be immpossible.

**Comment by janat08** [comment]
https://forums.meteor.com/t/vue-meteor-accounts/32695/10?u=janat08

I suppose this is a solution with vuex.

**Comment by Akryum** [comment]
In components you can use the meteor data directly:

```javascript
meteor: {
  data: {
    user () {
      return Meteor.user()
    },
  }
},
```

**Comment by janat08** [comment]
Oh lol, I was trying to also make data: { user: {} }} available in vue. Any how it works even I'm accessing Meteor.user properties in vue if I guard against Meteor.user() being undefined. Any chance that the work arounds in alanning roles could be implemented so that meteor evaluates first to get rid of guard boilerplate.

**Comment by Akryum** [comment]
Which workaround is it?

**Comment by janat08** [comment]
https://github.com/alanning/meteor-roles/issues/218
If you land on page where you access property of meteor data within template you make sure that router loads meteor data first, I don't understand what was actually proposed in there. Otherwise maybe making vue data parity (vue: data, vue: meteor: data) work as safeguard against first page load with property access from meteor data while also making meteor.user() work when you use vue: data parity.

**Comment by Akryum** [comment]
You can use [global navigation guards](http://router.vuejs.org/en/advanced/navigation-guards.html) that will make the router wait for the user subscription to be ready.

**Comment by janat08** [comment]
#115 must be related, will try to come back with how to actually access subscriptions.

**Comment by janat08** [comment]
http://www.regotcha.com/post/vue-js-route-guarding

This is in no way simple given I can't even tell how I would go about accessing unique subscriptions outside of component, other than just calling them within the guard which kind of defeats the purpose of this package. How about some voodoo to adapt subscription declarations to router guard (and autopublish one wtv it is actually registered as).

**Comment by Akryum** [comment]
I don't see what is the problem regarding subscribing to publications globally with standard Meteor functions.

**Comment by janat08** [comment]
Per route ones won't be that bad, but you could automatically register component declared subscriptions with the global guard so that it just works (in my wishful thinking). I imagine for me that may prove to be a painful exercise, doing component guards alone :P.
