### ISSUE TITLE
gql is not defined

### ISSUE THREAD

**Issue by jimmack1963** [Akryum/vue-meteor#136]
I don't use Apollo.  Downloaded & installed both Meteor & this library (thanks) today, so current versions.  Dealt with all messages on meteor startup to upgrade versions of graphql-server-express & graphql-tools. 

See this in the console instead of any display:
gql is not defined
  at Apollo.vue:52
    at meteorInstall.imports.ui.Apollo.vue (Apollo.vue:38)
    at fileEvaluate (modules-runtime.js?hash=0969a31…:207)
    at require (modules-runtime.js?hash=0969a31…:130)
    at app.js?hash=2536dfa…:1227

**Comment by Akryum** [comment]
You may need `graphql-tag`. But I'm sorry I don't support issues unrelated to vue-apollo or vue-meteor. Please try on the meteor forum.

**Comment by jimmack1963** [comment]
To be clearer, I had only checked out vue-meteor and was trying to get it to run, without any personal modifications other than the tweaks I mentioned above.

Your Vue-meteor project has a dependency problem I'm not clever enough to fix.

So, in my clone of your project. I also typed meteor npm install graphql-tag, was able to start the meteor command, and still in the console get the 'gql is not defined error at the same place.  But now, I got a message that apollo-client needed 0.8.0.

I've tried responding to every message with an updrade in versions, but I still fail.  Cascading updates led me to think I had to install apollo-client 0.8.0, but your vue-apollo seems to want 0.5.0.

I'd guess that in your dependencies, when installed today, something has changed from when you did it but the version isn't locked, so the newer version isn't happy.  I gather yarn is a little more helpful with that than npm,  Please let me know if I can help tracking it down, and thank you for your great work on this!
