### ISSUE TITLE
<router-link> : TypeError: Cannot read property 'resolve' of undefined on production mode

### ISSUE THREAD

**Issue by nizulzaim** [Akryum/vue-meteor#138]
It look like `<router-link>` cannot being used in production mode and end up error. It will not giving me error if  i load the page but when i load to other page and navigate to page that have `<router-link>` element, it will give the error. I am using VueRouter 2.3.0 and akryum:vue-router2@0.02. The bad thing is the element will not show up.

![screenshot 2017-03-10 05 56 36](https://cloud.githubusercontent.com/assets/9782607/23772700/ebec19c4-0556-11e7-9b82-1782a9667677.png)

This is the simplest code that i used and my configuration of vue router is exactly look like your example:

```
<div class="font-body no-margin">
         Wow this look amazing bla bla <router-link to="/components/cards">Hahaha</router-link>
</div>
```

app.js
```
import { Vue } from 'meteor/akryum:vue';
import router from '/imports/client/router.js';
import AppLayout from '/imports/client/views/AppLayout.vue';
import VueHead from 'vue-head';
import VueHighlightJS from 'vue-highlight.js';
import ViuUI from 'meteor/skynightz93:viu-ui';
import 'highlight.js/styles/monokai.css';

Vue.use(VueHighlightJS);
Vue.use(VueHead);
Vue.use(ViuUI);

Meteor.startup(() => {
    new Vue({
        router: router.start(),
        render: h => h(AppLayout),
    }).$mount('app');
});
```

**Comment by nizulzaim** [comment]
Found the issue:

```
<scroll-bar>
   <span>
      <router-view ></router-view>
   </span>
</scroll-bar>
```

Component ScrollBar create in meteor packages and i wrap the `router-view` in this components. This is my scrollbar template where i already remove the script content to make sure it is only because of wrapping 

```
<template>
    <div class="scrolllbar">
        <slot></slot>
    </div>
</template>    
```

and i am also try to create MyScrollBar.vue in the same folder AppLayout (imports/ui/MyScrollBar.vue) as in your example `vue-meteor-router` :

```
<my-scroll-bar>
   <router-view ></router-view>
</my-scroll-bar>
```

Still it will not fix and give same error. I dont know if it is problem because of your package or vue-router itself. Note that this problem only occur if i am using in production mode.

**Comment by Akryum** [comment]
I'll try to reproduce that this weekend.

**Comment by nizulzaim** [comment]
I think I end up creating two instance of Vue. When i running `this.$root.$el` & `this.$parent.$el`, the value is not same as the first load which is only get the root of component that call it. If you see here in my console in development mode: 

![screenshot 2017-03-11 18 54 14](https://cloud.githubusercontent.com/assets/9782607/23822662/3f29035a-068c-11e7-8440-b3d696435cda.png)

And here is my package.js where i call `akryum:vue-component@0.8.10`. If i dont use this package, information about `You are running Vue in development mode, bla bla` only show once but i cant import my .vue files.

```
Package.onUse(function(api) {
    Npm.depends({
        'velocity-animate': '1.4.2',
        'mobify-plugin': '4.0.0',
        'is-touch': '1.0.2',
        'slick-carousel': '1.6.0',
    });
    api.versionsFrom('1.4.1.1');
    api.use('ecmascript');
    api.use(['jquery','akryum:vue-component@0.8.10'], 'client');
    api.mainModule('viu-client.js', 'client');
    api.addFiles(['client/css/materialdesignicons.css', 'client/css/viu.css', 'client');

    api.addAssets([
        ...//something here
    ], ["client"]);
});
```

**Comment by Akryum** [comment]
What is displayed in the Vue devtools?

**Comment by nizulzaim** [comment]
i cant use vue dev-tools in production mode? how i can enable it??

**Comment by Akryum** [comment]
Oh yeah right, I forgot you were in production mode. You don't have two root instances in dev mode though?

**Comment by nizulzaim** [comment]
the image i show you is in dev mode but although it print out `You are running Vue in development mode, bla bla`, i dont have any error like i cannot get this.$root.$el. That's why i though my code is ok. But when trying to release my code, i got this error. You can go here and click Show Menu. [https://doc.devsign.my/components/menu](https://doc.devsign.my/components/menu). Try to navigate to other page and back to that page. You can see my menu is not at right position because this.$root.$el is not point to `<app></app>` but point out to `<router-view>` that calling this menu. In this case this.$root.$el, `<div class="appbar-padding" style="height: 947px;"></div>` is the one who call this components.

**Comment by nizulzaim** [comment]
Here is my repo [https://github.com/DevsignStudio/viu](https://github.com/DevsignStudio/viu)

**Comment by Akryum** [comment]
You can enable devtools in production mode with `Vue.config.devtools = true` 😄

**Comment by nizulzaim** [comment]
Ok thanks. I search and only found Vue.config.debug = true. Thats why i cant enable it. Thank you.

**Comment by nizulzaim** [comment]
Hi, here is my testing in devtools that I think difficult to understand but I already create reproduction repo for you hoping you find something. Here is my repo [https://github.com/DevsignStudio/viu-doc](https://github.com/DevsignStudio/viu-doc).

![screenshot 2017-03-12 13 20 22](https://cloud.githubusercontent.com/assets/9782607/23829208/b45a5850-0726-11e7-9981-a5aac48d2c4e.png)

If you look here there is nothing to worry. No error, Look fine for me. But then when I select Raised Button Element:

![screenshot 2017-03-12 13 22 32](https://cloud.githubusercontent.com/assets/9782607/23829212/00f6dea4-0727-11e7-9e01-914d684cfec6.png)

Now you can see `<Root>` and `<RaisedButton>` are bind together means that whenever i try to run `$vm0`, the root element will print out <Root> not the <RaisedButton>.

**Comment by nizulzaim** [comment]
Now, what about if I am creating duplicate of RaisedButton? Do it still bound to Root? See my testing:

![screenshot 2017-03-12 13 32 45](https://cloud.githubusercontent.com/assets/9782607/23829255/77ba2180-0728-11e7-8c40-5dcebb42a52b.png)

![screenshot 2017-03-12 13 33 00](https://cloud.githubusercontent.com/assets/9782607/23829256/7d968f58-0728-11e7-9564-eee0b947ffd5.png)

**Comment by nizulzaim** [comment]
I will give more what i am testing. If i am navigate to page1 and back to home:

![screenshot 2017-03-12 13 41 03](https://cloud.githubusercontent.com/assets/9782607/23829296/b547e09a-0729-11e7-9f47-f989d72bf201.png)

And do once more time:

![screenshot 2017-03-12 13 41 26](https://cloud.githubusercontent.com/assets/9782607/23829298/bef12b9c-0729-11e7-98e6-a606bad3073c.png)

**Comment by Akryum** [comment]
Thanks! I'll try it soon.

**Comment by nizulzaim** [comment]
Just to let you know that i am able to create npm module using my code without changing RaisedButton code at all and test it again in meteor --production. So i am now have narrow it down to your packages because of using it in meteor packages. Glad hear you are going to test it.

**Comment by Akryum** [comment]
I have [forked your repo](https://github.com/Akryum/viu/tree/dev), updated all the packages (including mine), uncommented the ScrollBar component code and run `meteor --production`. Everything seems to work fine.

**Comment by Akryum** [comment]
[Compare the two branches](https://github.com/DevsignStudio/viu/compare/dev...Akryum:dev).

**Comment by nizulzaim** [comment]
Hi, do you able to reproduce the error? Just curious.

**Comment by nizulzaim** [comment]
Tested and will close this now. Thank you so much for helping me here.
