### ISSUE TITLE
Invalid Expression when install vue-auto-form component 

### ISSUE THREAD

**Issue by YouSour** [Akryum/vue-meteor#139]
Recently I have tried [vue-auto-form](https://www.npmjs.com/package/vue-auto-form). but i got an error like this. [ 'invalid expression: :selected="input.defaultValue.indexOf(item.value)  data-v-042b3740> -1"' ]. I have no idea what the error but i believe it related to component stuff. appreciate for helping

**Comment by Akryum** [comment]
Try to ignore `node_modules` folder with a `.vueignore` file in your project root directory. [Doc](https://github.com/Akryum/vue-meteor/tree/master/packages/vue-component#ignore-files)
