### ISSUE TITLE
'Unexpected Reserve Word'  when importing component from node_modules

### ISSUE THREAD

**Issue by mingliang7** [Akryum/vue-meteor#140]
i have placed .vueignore file inside my app directory and i also installed some components from npm and i cant import it. see pics below.
![unexpected-reserve-word](https://cloud.githubusercontent.com/assets/5500858/23841362/436515a4-07df-11e7-8318-caa361156467.png)

thanks in advance!

**Comment by Akryum** [comment]
You need to be sure to import the dist/compiled files of these packages, and not the source.

**Comment by Akryum** [comment]
[Documentation](https://github.com/Akryum/vue-meteor/blob/master/packages/vue-component/README.md#using-vue-npm-packages)

**Comment by mingliang7** [comment]
I have followed your doc.but still not work. i use this package from npm [vue-auto-form](https://www.npmjs.com/package/vue-auto-form). 
- this is my setup
![setup](https://cloud.githubusercontent.com/assets/5500858/23952528/48989ba4-09c4-11e7-8748-d80396908cda.png)

- this is error on my client 
![error](https://cloud.githubusercontent.com/assets/5500858/23952557/62761c2c-09c4-11e7-9c92-36d2f4ba3869.png)

**Comment by Akryum** [comment]
It seems that vue-auto-form doesn't bundle any distribution (there is only source code available), so it can't be used easily with meteor.

**Comment by mingliang7** [comment]
Thanks. I understood this
