### ISSUE TITLE
How to use npm packages like Keen-ui with vue-meteor?

### ISSUE THREAD

**Issue by green-coder** [Akryum/vue-meteor#141]
I am trying to use [`keen-ui`](https://github.com/JosephusPaye/Keen-UI) using `vue-meteor`. I am installing it using `meteor npm install keen-ui --save`, which is probably very wrong because meteor complains with a lot of the following errors:

(I already did `meteor add akryum:vue-sass`)

```bash
[vue-component] Error while compiling in tag <style> using lang scss -> in node_modules/keen-ui/src/UiAlert.vue at line 86
{ [Error: Unknown import (file not found): util]
  formatted: 'Error: Unknown import (file not found): util\n        on line 1 of node_modules/keen-ui/src/styles/imports.scss\n>> @import \'util\';\n   --------^\n',
  message: 'Unknown import (file not found): util',
  column: 9,
  line: 1,
  file: '/Users/Xxx/Code/myProject/node_modules/keen-ui/src/styles/imports.scss',
  status: 1 }
```

Here is the content of the `imports.scss` file:
```scss
@import 'util';
@import 'variables';
@import 'mixins';
```

In a general way, I am wondering how to properly use/import an external npm library with `vue-meteor`.

**Comment by green-coder** [comment]
Supposing that I am adding `keen-ui` the right way, the issue seems to be related to import paths resolution in npm packages. Related to #133, maybe.

I am using the latest packages available from meteor's update command.

**Comment by Akryum** [comment]
You did install it the right way. You just need a bit of additional setup.
Add a `.vueignore` in the project root with the following content:

```
node_modules/
```

Then install the plugin in your app using the dist files:

```javascript
import 'keen-ui/dist/keen-ui.min.css'
import KeenUI from 'keen-ui/dist/keen-ui.min.js'
Vue.use(KeenUI)
```

**Comment by green-coder** [comment]
I tested your solution, and it works fine. Merci beaucoup !

**Comment by Akryum** [comment]
https://github.com/Akryum/vue-meteor/blob/master/packages/vue-component/README.md#using-vue-npm-packages
