### ISSUE TITLE
vue2-hot.js error on file changes at vue-component@=0.8.11

### ISSUE THREAD

**Issue by gustojs** [Akryum/vue-meteor#142]
The following error shows up with `vue-component@=0.8.11`. The same code works fine when I revert to `0.8.10`.

Both Meteor 1.4.2.7 and 1.4.3.2. 
Vue 2.2.4.

Happens at any file change (triggers the error and refresh instead of module replacement)

Did anybody encounter same thing?

```
[HMR] Rerendering imports/ui/layouts/DefaultLayout.vue
vue2-hot.js:92 TypeError: Cannot read property 'Ctor' of undefined(…)(anonymous function) 
vue2-hot.js:93 Something went wrong during Vue component hot-reload. Full reload required.
vue2-hot.js:101 Uncaught TypeError: Cannot read property 'Ctor' of undefined
```

**Comment by gustojs** [comment]
Looks like it resolved somehow after multiple reverts in both ways. I'll keep it open for a day to see if anybody else had similar situation. Then I'll close it.

**Comment by gustojs** [comment]
I created a new project at Meteor 1.4.3.2.
```
meteor create hmr-test
meteor cd hmr-test
meteor add vue-component
meteor npm install vue vue-meteor-tracker vue-router vuex
meteor npm update
```
The error still encounters with vue-component 0.8.11, doesn't encounter with 0.8.10.

**Comment by gustojs** [comment]
Repro https://github.com/gustojs/hmr-error-repro

**Comment by unsama** [comment]
**select: function () {
            var self = this;
            self.$http.post("/purchase/rfq-table", {
                "username": self.options,
            }).then(function(res){
                var data = res.body.result;
                self.tabledata = [];
                if(data.length > 0){
                    data.forEach(function(val) {
                        self.tabledata.push({
                            "data": [
                                val.name,
                                val.schedule_date,


                            ],
                            "url": "/purchase/RQ/"+val.id,
                        });
                    });
                    console.log(self.tabledata);
                }
                //self.options =res.body.data;

            },function(err){
                alert(err);
            });
        },**

> **## Uncaught (in promise) TypeError: Cannot read property 'length' of undefined**


i dont know the error please help me out this.

**Comment by unsama** [comment]
**select: function () {
            var self = this;
            self.$http.post("/purchase/rfq-table", {
                "username": self.options,
            }).then(function(res){
                var data = res.body.result;
                self.tabledata = [];
                if(data.length > 0){
                    data.forEach(function(val) {
                        self.tabledata.push({
                            "data": [
                                val.name,
                                val.schedule_date,
                            ],
                            "url": "/purchase/RQ/"+val.id,
                        });
                    });
                    console.log(self.tabledata);
                }
                //self.options =res.body.data;
            },function(err){
                alert(err);
            });
        },**

> **## Uncaught (in promise) TypeError: Cannot read property 'length' of undefined**


i dont know the error please help me out this.
