### ISSUE TITLE
Router is not a constructor

### ISSUE THREAD

**Issue by alexandesigner** [Akryum/vue-meteor#146]
Before this problem did not happen. **Today**, when I was cloning the project: https://github.com/Akryum/meteor-vue2-example-routing

I'm having this problem on my console

``Uncaught TypeError: Router is not a constructor``

![pic](https://cloud.githubusercontent.com/assets/3044907/24215813/ba6b0dbc-0f18-11e7-828a-22e9a4383705.png)

What can it be?

**Comment by Akryum** [comment]
The [API changed](https://github.com/Akryum/vue-meteor/blob/master/packages/vue-router2/CHANGELOG.md#010) and I didn't have time to update this example yet.
