### ISSUE TITLE
Is it possible to only load components css if it is mounted?

### ISSUE THREAD

**Issue by j-jackson** [Akryum/vue-meteor#150]
I have an app thats allows the user to choose from a few different themes/templates which all have their own components, so I only want to load the components css if the user has selected it. i.e there might be 8 Navbar components but only one can be active so I don't want to load the other 7.

from my brief testing with the demo project, it looks like it bundles all the css like a standard meteor app. Is there a way around this?

Perhaps #114 will help with this?

**Comment by j-jackson** [comment]
I just had a look at the [vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0) demo and  it looks like they are automatically inlining CSS used by rendered components. I guess this is probably webpack right?

**Comment by Akryum** [comment]
Yes, it's webpack. Maybe Meteor 1.5 code-splitting could help?

**Comment by Morganjackson** [comment]
Yeah thats what I was thinking, but then I cam across [meteor-client-bundler](https://github.com/Urigo/meteor-client-bundler) .  Have you had a look at it? looks like it would give us the best of both worlds with vue-cli and meteor as an api with accounts etc.

**Comment by gustojs** [comment]
@Morganjackson meteor-client-bundle only lets us to use Meteor on the client which is very unfortunate imho.

So the advantage of meteor-client-bundle is support for testing with webpack goodies, the advantage of Vue+Meteor is SSR.

**Comment by Morganjackson** [comment]
Thanks for the clarification @gustojs. So your saying you can use meteor-client-bundler with something like vue-cli, but it wont work if you want SSR?

**Comment by Morganjackson** [comment]
@gustojs bummer, I just read your comment on the forums in regards to nuxt.

Just out of curiosity, could you use apollo for data to get around SSR but still use MCB for accounts?
