### ISSUE TITLE
Supporting lang="pug"

### ISSUE THREAD

**Issue by green-coder** [Akryum/vue-meteor#151]
`Jade` was renamed to `pug`. For the templates, could you support `lang="pug"` as well?

**Comment by laosb** [comment]
Should be simple as adding `pug` as an alias on https://github.com/Akryum/vue-meteor/blob/master/packages/vue-jade/vue-jade.js#L7 ?

**Comment by Akryum** [comment]
`meteor add akryum:vue-pug`
