### ISSUE TITLE
CORS Error vue-component

### ISSUE THREAD

**Issue by frco9** [Akryum/vue-meteor#152]
I have add `akryum:vue` and `akryum:vue-component` on an existing project with Blaze. 
 I get the following errors when trying to load the [following component](https://github.com/Akryum/meteor-vue-blaze/blob/master/imports/ui/Widget.vue) inside my code : 

<img width="492" alt="capture d ecran 2017-03-29 a 11 49 19" src="https://cloud.githubusercontent.com/assets/60847/24448989/3ddccfe8-1476-11e7-8b86-0f8be15e951e.png">

Any idea why ?

**Comment by Akryum** [comment]
What is the server console output?

**Comment by frco9** [comment]
There isn't any : 

```

=> Started proxy.
=> Meteor 1.4.3.2 is available. Update this project with 'meteor update'.
   [HMR] Dev server listening on port 3003
=> Started MongoDB.
I20170329-12:05:41.671(2)? Kadira: Successfully connected
I20170329-12:05:41.718(2)? Kadira: completed instrumenting the app
=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by Akryum** [comment]
Try installing the last compatible version:

`meteor npm i -S vue@2.2.4`

**Comment by frco9** [comment]
Still the same : 

<img width="489" alt="capture d ecran 2017-03-29 a 12 12 12" src="https://cloud.githubusercontent.com/assets/60847/24449870/faf5dcf8-1478-11e7-8ba0-69eac18c48fb.png">

**Comment by frco9** [comment]
My bad, the 3003 port was already in use by another server. The weird thing is that I didn't get an `EADDRINUSE` error :/ 

Thanks !
