### ISSUE TITLE
Uncaught Error: Cannot find module 'http'

### ISSUE THREAD

**Issue by nilsi** [Akryum/vue-meteor#153]
Trying to migrate to Vue from Blaze but getting the following error in Chromes console. Not sure how I can debug this. I tried installing http both with `meteor npm install http --save` and `meteor add http` but no difference. I also removed a few packages like jQuery but so far I cant find the reason.

```
Uncaught Error: Cannot find module 'http'
    at require (modules-runtime.js?hash=0969a31…:133)
    at new XMLHttpRequest (akryum_vue-component-dev-client.js?hash=32ed31e…:6877)
    at akryum_vue-component-dev-client.js?hash=32ed31e…:5684
    at meteorInstall.node_modules.meteor.akryum:vue-component-dev-client.node_modules.engine.io-client.lib.transports.polling.js (akryum_vue-component-dev-client.js?hash=32ed31e…:5686)
    at fileEvaluate (modules-runtime.js?hash=0969a31…:207)
    at require (modules-runtime.js?hash=0969a31…:130)
    at meteorInstall.node_modules.meteor.akryum:vue-component-dev-client.node_modules.engine.io-client.lib.transports.polling-xhr.js (akryum_vue-component-dev-client.js?hash=32ed31e…:5243)
    at fileEvaluate (modules-runtime.js?hash=0969a31…:207)
    at require (modules-runtime.js?hash=0969a31…:130)
    at meteorInstall.node_modules.meteor.akryum:vue-component-dev-client.node_modules.engine.io-client.lib.transports.index.js (akryum_vue-component-dev-client.js?hash=32ed31e…:5179)
```

**Comment by Akryum** [comment]
Is it the nodejs http module?

Le jeu. 30 mars 2017 17:27, Nicklas Nilsson <notifications@github.com> a
écrit :

**Comment by nilsi** [comment]
Yes, it is. Seems like its a problem with meteor and not this package. Just confusing since it was working fine previously.

**Comment by Akryum** [comment]
I mean the nodejs http API that you may be trying to use client side.

Le jeu. 30 mars 2017 17:57, Nicklas Nilsson <notifications@github.com> a
écrit :

**Comment by nilsi** [comment]
Im not calling or using http anywhere in my project. I use https in a few places though. So I thought it had to do with a package I have installed. 

If I click on `at new XMLHttpRequest (akryum_vue-component-dev-client.js?hash=32ed31e…:6877)`I can see the place where its being called but it does not help me.

 ```
*                                                                                                                     // 33
 * @param {Object} opts optional "options" object                                                                      // 34
 */                                                                                                                    // 35
                                                                                                                       // 36
function XMLHttpRequest(opts) {                                                                                        // 37
  /**                                                                                                                  // 38
   * Private variables                                                                                                 // 39
   */                                                                                                                  // 40
  var self = this;                                                                                                     // 41
  var http = require('http');                                                                                          // 42
  var https = require('https'); 
```

**Comment by Akryum** [comment]
This seems like server-side code to me here, with the [http](https://nodejs.org/dist/latest-v4.x/docs/api/http.html) and [https](https://nodejs.org/dist/latest-v4.x/docs/api/https.html) node module in the node API.

**Comment by laosb** [comment]
After updating to Meteor 1.4.3.2, I came across similar problems, but actually I'm having clientside Vue components loaded on server, causing no-`document` errors. Do you use 1.4.3.2 as well? My app is fine if I stick to 1.4.3.1.

**Comment by nilsi** [comment]
I got it working with 1.4.3.2 now. I removed `http` from `.meteor/packages `. I also reinstalled my modules by `$ rm -r node_modules` and removed `http` and `https` from root `packages.js` file.

**Comment by vadkasevas** [comment]
You need meteor-node-stubs installed:
meteor npm install --save meteor-node-stubs
