### ISSUE TITLE
working with webpack?

### ISSUE THREAD

**Issue by funkyLover** [Akryum/vue-meteor#158]
forgive me for opening this issue, actually, i haven't yet to try this project, just get some confuse, if this isn't the right way to put question, please close this issue without hesitation.

i work with a project with vue(with webpack) and meteor, like this [repo](https://github.com/thereactivestack-legacy/meteor-webpack/tree/master/packages/webpack) dose, work fine but something make my mind a mess. 

1) the origin process of front-end develop with meteor : `edit client side code` -> `meteor build` -> `build done and make browser reload whole page`.
2) when work with webpack, it becomes: `edit client side code` -> `meteor build` -> `webpack build` -> `build done and make browser reload whole page`

the font-end development still base on meteor build process. is it possible make that : `edit client side code` -> `can hmr?` -> `yes, webpack build, and don't reload whole page` -> `no, webpack build, and reload whole page`? just like front-end development without meteor! i need more scalability with front-end(i.e. code-splitting like webpack dose, custom app structure.....)

i have try `vue-meteor-demo`, and it work just like above! great work!`vue-meteor` dose not require webpack, can i integrate with webpack when i want(or need) to do.

**Comment by funkyLover** [comment]
another example [vue-webpack-meteor-example](https://github.com/vuejs/vue-webpack-meteor-example).

just make: `webpack watch` -> `client side build` -> `dist pubilc` -> `meteor build` -> `reload whole page`. a simple trick but dosen't hlep.

**Comment by Akryum** [comment]
Using webpack is not necessary (nor recommended) with `vue-meteor`. It already provides most of the things you need (like HMR), and Meteor is getting code-splitting in the 1.5 release.

**Comment by funkyLover** [comment]
thank @Akryum !

**Comment by gustawdaniel** [comment]
Why using `webpack` is not recommended with `vue-meteor`?

And how to add configuration like this 

```
      {
        test: /\.js$/,
        loader: 'babel-loader',
-       include: [resolve('src'), resolve('test')]
+       include: [
+         resolve('src'),
+         resolve('test'),
+         resolve('node_modules/vue-echarts'),
+         resolve('node_modules/resize-detector')
+       ]
      }
```

to file that in pure `vue` project is called `build/webpack.base.conf.js`

Question is inspired by README of

https://github.com/ecomfe/vue-echarts

but I have seen some other examples of vue packages that recommend some changes in webpack file.

**Comment by gustawdaniel** [comment]
I found solution in 

https://github.com/meteor-vue/vue-meteor/issues/207

Instead of importing `vue` file

    import ECharts from 'vue-echarts/components/ECharts'

We should import `js` file

    import ECharts from 'vue-echarts/dist/vue-echarts'
