### ISSUE TITLE
Official typescript support

### ISSUE THREAD

**Issue by Akryum** [Akryum/vue-meteor#16]
Need #14

**Comment by nathantreid** [comment]
FYI I'm working on a [typescript plugin](https://github.com/nathantreid/meteor-vue-component/tree/typescript) that uses [barbatus:typescript-compiler](https://github.com/barbatus/typescript-compiler). Not sure if you want this as a PR on core or as a community package.
Compilation is working (although I want to test it a lot more) - but I also plan to add support for barbatus's `tsconfig.json` before I consider it ready for release.

**Comment by Akryum** [comment]
That's awesome! There is room for community package here, so I don't think it's necessary to merge it as a PR. I'll leave this choice to you.

**Comment by Akryum** [comment]
Now supported thanks to @nathantreid 
https://github.com/nathantreid/vue-css-modules
