### ISSUE TITLE
Can't import VueMaterial in imports folders

### ISSUE THREAD

**Issue by lastday4you** [Akryum/vue-meteor#160]
i tired to add the npm VueMaterial in to my component it is working fine if all my component it is in client folder but when i move to imports folder these error will appear
<img width="1280" alt="screen shot 2017-04-19 at 10 51 06 am" src="https://cloud.githubusercontent.com/assets/10150321/25162626/760d65ca-24ee-11e7-814c-c8d8885cad7d.png">
<img width="883" alt="screen shot 2017-04-19 at 10 51 36 am" src="https://cloud.githubusercontent.com/assets/10150321/25162653/a74cd7ce-24ee-11e7-8e6a-09b576632016.png">
<img width="756" alt="screen shot 2017-04-19 at 10 51 12 am" src="https://cloud.githubusercontent.com/assets/10150321/25162654/a7901d9a-24ee-11e7-99d0-8163b3b76f3d.png">

**Comment by Akryum** [comment]
Try to move the `Vue.use(VueMaterial)` code to your main javascript file before creating the root instance (`new Vue(...)`).

**Comment by lastday4you** [comment]
it is still error, if i move all the import in to main js the component that i use in Navbar will not be render.  i think it is Vuecompiler error because there was server error if i import css in the component in imports folder

**Comment by lastday4you** [comment]
thank it work now. i was using it in a wrong way
