### ISSUE TITLE
Why should we use vue-router2 meteor package instead of native npm version vue-route?

### ISSUE THREAD

**Issue by zhongqf** [Akryum/vue-meteor#171]
Is there any benefits or differences by using `vue-route2` meteor package with `meteor add vue-router2`,
instead of using native `vue-route` npm package with `meteor npm install vue-router`?
@Akryum

**Comment by Akryum** [comment]
See [this post](https://forums.meteor.com/t/code-separation-package-questions/35795/2?u=akryum).

**Comment by zhongqf** [comment]
@Akryum Thanks.
