### ISSUE TITLE
How to get `params` in `$route.matched`?

### ISSUE THREAD

**Issue by thearabbit** [Akryum/vue-meteor#176]
I would like to crate breadcrumbs from `$route.matched`, but in this object don't have `params prop`. How to get `params` in `$route.matched`?
Please help me

**Comment by thearabbit** [comment]
I try
```js
routes: [
    { path: '/hello/:name', component: Hello, props: true }, // Pass route.params to props (in example of document)
```
Get `$route.matched` in layout
```js
console.log(this.$route.matched);
------
[{
   beforeEnter:(...)
   components:(...)
   props:{default:true} // Can't get params
}
]
------
<router-link to="/hello/Theara">Link</router-link>
```

**Comment by Akryum** [comment]
Hey! Thank you for filling your issue, but it seems not related to vue-meteor. Please ask your questions about vue-router on the [official forums](https://forum.vuejs.org/). :smile:

**Comment by thearabbit** [comment]
Thanks for your reply.
