### ISSUE TITLE
Silly question: What is that sexy color scheme?

### ISSUE THREAD

**Issue by Herteby** [Akryum/vue-meteor#185]
<img src="https://camo.githubusercontent.com/14e5f4477f49cf0fc0d8f228facb17772a0b1025/687474703a2f2f626c6f672e6576616e796f752e6d652f696d616765732f7675652d636f6d706f6e656e742e706e67">

**Comment by nilsi** [comment]
I think thats most likely `One Dark` theme in Atom since it looks very similar to the one I use. I also use the package `language-vue` but don't think that affects the look of it.

**Comment by Herteby** [comment]
@nilsi I thought so too at first. The colors are the same, but they are a lot more vibrant than One Dark.

**Comment by nilsi** [comment]
![screen shot 2017-05-15 at 5 56 28 pm](https://cloud.githubusercontent.com/assets/793881/26049989/f8cd9e18-3997-11e7-924a-0108dea235e6.png)
Hum your right, the colors differ a bit.

**Comment by Akryum** [comment]
It's a question you could ask on the Vue forums since it's a picture borrowed from the Vue doc. :smile:

**Comment by mwarren2** [comment]
Might be AfterGlow plugin for IntelliJ

**Comment by Herteby** [comment]
I just saw Evan You use it himself in this talk 😄 
https://youtu.be/7ezqhrk1ABI?t=26m21s

@mwarren2 Doesn't look like their screenshots though.

**Comment by mwarren2** [comment]
@Herteby for what it's worth the AfterGlow plugin for IntelliJ is pointless (I just tried it) because it only affects the sidebar on the left. 
However the original - made for SublimeText - looks a good candidate. But I don't use SublimeText so I can't vouch for it.

**Comment by Herteby** [comment]
@nilsi I found the answer! 😄 
I had the (I must say genius) idea of searching Evan You's repositories for "sublime", and found that he had forked equinusocio/material-theme!
The color scheme he uses is an old version from 2015
https://github.com/yyx990803/material-theme/blob/master/schemes/Material-Theme.tmTheme
