### ISSUE TITLE
cannot pass data to constructor with render function

### ISSUE THREAD

**Issue by christophmayrhofer** [Akryum/vue-meteor#197]
I render a vue component with the following code:

```
        new Vue({
            el: 'vuecomponent',
            data: { id: 'abc' },
            render: h => h(vueComponent)
        })
```

It is displayed correctly. but id is not available.
I have tried:
id
this.id
this.data.id
this.$data.id
$data.id
data.id

each in methods, mounted & template html

**Comment by Akryum** [comment]
Are you using arrow functions that makes you loose the component `this` context?

**Comment by christophmayrhofer** [comment]
I just realized that it works when I use `this.$parent.$data.id`.
Seems unintuitive but works

**Comment by Akryum** [comment]
This is because `vueComponent` is rendered as a child to your root Vue instance.

If you want it to be the root component, try:

```javascript
new Vue({
  el: 'vuecomponent',
  data: { id: 'abc' },
  // JavaScript Properties copy
  ...vueComponent,
})
```

Or:

```javascript
new Vue({
  el: 'vuecomponent',
  data: { id: 'abc' },
  // Vue component definition extension
  extends: vueComponent,
})
```

**Comment by christophmayrhofer** [comment]
perfect. Thank you
