### ISSUE TITLE
FOUC with vue-component & vue-sass

### ISSUE THREAD

**Issue by SnooHD** [Akryum/vue-meteor#213]
When loading a component i get a FUOC (flash of unstyled content).
I have this issue with all of my Vue components.

Is there anything that can be done to prevent this?

**Comment by SnooHD** [comment]
My guess is that this only happens in development mode, can someone confirm this?
I don't a hosting at this moment, so i can't test it.

**Comment by Akryum** [comment]
See [this comment](https://github.com/Akryum/vue-meteor/issues/109#issuecomment-277065298).
