### ISSUE TITLE
Vuex 2.x

### ISSUE THREAD

**Issue by Akryum** [Akryum/vue-meteor#65]
TODO

**Comment by janat08** [comment]
Give it to me

**Comment by green-coder** [comment]
I am suggesting to add a warning at the top of the README.md file to inform people that the module is using a very old version of `vuex`.

**Comment by janat08** [comment]
Yes, I also spent a while trying to "work around" the incompatibility.

**Comment by Akryum** [comment]
I deprecated the package in favor of [vue-supply](https://github.com/Akryum/vue-supply).

**Comment by green-coder** [comment]
I forgot a link to your Vuex project [there](https://github.com/Akryum/vue-meteor-tracker/blame/master/README.md#L249).

**Comment by Herteby** [comment]
So you don't recommend using Vuex with Meteor?

**Comment by janat08** [comment]
You can still use vuex as with generic instruction provided by vuex guide.

**Comment by Herteby** [comment]
Thanks, I was more asking about an opinion. I'm new to Vue, coming from Meteor, and I don't know yet what role Vuex would serve in a Meteor-Vue app. And it seemed like Akryum was saying that you vue-supply would serve as a replacement for Vuex (interacts better with Meteor?)

**Comment by janat08** [comment]
Vue-supply extends in the same way that this package did by offering tracker and subscriptions I belief. The reason why the change is that vue-supply is likely whole lot more vuex base agnostic making it easier to maintain.
