### ISSUE TITLE
Sass imports in .vue components

### ISSUE THREAD

**Issue by bduff9** [Akryum/vue-meteor#76]
It looks like the sass import logic is not totally working for the style section of the .vue files.  First, the documentation to single file components is currently a 404 in a couple places on the URL to the vue docs (https://vuejs.org/guide/application.html#Single-File-Components).  I believe it should be https://vuejs.org/guide/single-file-components.html.

Second, the docs indicate you should be able to import with @import ~imports/ui/colors.sass, however unless that is a specific thing to lang="sass" in your plugin, there should be quotes around the import as currently I get a compile error that says `@import directive requires a url or quoted path` in my lang="scss" import.

Finally, outside of the above, the import logic seems to differ from how sass imports work.  For instance, if I put in `@import "./colors";` it should look in the current directory for a file with a name matching either colors or _colors with an extension of .scss or .sass.  Currently, doing anything other than including the entire file name, i.e. `@import "_colors.scss";` causes the compile to fail with a file not found.  While this is incorrect on its own, it actually seems to be a bigger problem because even if I put in the full filename in my .vue file, if the file I am importing has an import, that will also fail.

Case in point, I am using bulma for my css, and I need to import a variable from its package (~node_modules/bulma/scss/utilities/_variables.scss).  Even once I put in that entire path into my import, I get a compile error that one of the files that the import is importing is not found.

While I think all import logic should be fixed, I think that import logic of files you are importing is a bigger deal as I do not control how those imports are structured (as they are in .scss files and are valid imports for that language).

I'm not sure if it will help, but here is the full error output I am currently getting when trying to import the variables file:

```
[vue-component] Error while compiling in tag <style> using lang scss -> in imports/ui/Login.vue at line 138
{ [Error: Unknown import (file not found): ./functions]
  formatted: 'Error: Unknown import (file not found): ./functions\n        on line 1 of node_modules/bulma/scss/utilities/_variables.scss\n>> @import "./functions";\n   --------^\n',
  message: 'Unknown import (file not found): ./functions',
  column: 9,
  line: 1,
  file: 'C:/gift-list/node_modules/bulma/scss/utilities/_variables.scss',
  status: 1 }
Exception in callback of async function: TypeError: Cannot read property 'styles' of null
    at hotCompile (packages/vue-component/plugin/vue-compiler.js:429:9)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
[vue-component] Error while compiling in tag <style> using lang scss -> in imports/ui/Login.vue at line 146
{ [Error: Unknown import (file not found): ./functions]
  formatted: 'Error: Unknown import (file not found): ./functions\n        on line 1 of node_modules/bulma/scss/utilities/_variables.scss\n>> @import "./functions";\n   --------^\n',
  message: 'Unknown import (file not found): ./functions',
  column: 9,
  line: 1,
  file: 'C:/gift-list/node_modules/bulma/scss/utilities/_variables.scss',
  status: 1 }
=> Errors prevented startup:

   While building for web.browser:
   imports/ui/Login.vue:146: [vue-component] Error while compiling in tag
   <style> using lang scss

=> Your application has errors. Waiting for file change.
```

**Comment by Micjoyce** [comment]
when build will get stuck at   Building plugin `vue-component-sass` ...  |

**Comment by nathantreid** [comment]
@bduff9 - For `sass`,  imports don't require the quotes. For `scss`, the quotes are required. http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html#id26
