### ISSUE TITLE
subModule.addResources in documentataion is inaccurate

### ISSUE THREAD

**Issue by janat08** [Akryum/vue-meteor#83]
On personal note, my component doesn't recognize actions imported from within nested submodules.

**Comment by Akryum** [comment]
Do you have an reproduction example?

**Comment by gustojs** [comment]
Does the same code work with Webpack/Browserify? Can you paste it? Are you sure it's an issue of Meteor integration?

**Comment by janat08** [comment]
I don't remember myself where inaccuracy is, closing.
