### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by M4v3R** [Akryum/vue-meteor#86]
The only one major feature missing from this package is server-side rendering. I will need it in my project shortly to render plain html files from .vue templates (basically I'm building a static website generator). @Akryum Are you planning to implement this in the near future? If not, can you point me in the right direction on how can I use Vue 2.0 SSR with Meteor?

**Comment by Akryum** [comment]
This is planned.

**Comment by nizulzaim** [comment]
Hi, I found this one and it look promising. I dont know if it is able to work with this project. `https://github.com/nuxt/nuxt.js`

**Comment by NicholasEli** [comment]
I am curious what that would look like at a basic level, using the example provided by bue for ssr until this is integrated into your project

**Comment by nizulzaim** [comment]
Any news?

**Comment by achtan** [comment]
@Akryum what is the estimated time of completion for SSR?

**Comment by janat08** [comment]
1.5 is suppose to be about ultra cool code splitting which could arguably be better unless the crawler.

**Comment by Akryum** [comment]
I'll start working on this soon as I need it for one of my own project. :smile:

**Comment by Akryum** [comment]
Things happening...

![image](https://cloud.githubusercontent.com/assets/2798204/24053405/3e4a428a-0b39-11e7-8142-9112c1029fe1.png)

**Comment by Akryum** [comment]
[First public release of vue-ssr](https://github.com/Akryum/vue-meteor/tree/master/packages/vue-ssr) (no vuex and apollo yet)!

Give it a try and share your experience with it!
