### ISSUE TITLE
Changing subscriptions rerenders everything

### ISSUE THREAD

**Issue by cpury** [Akryum/vue-meteor#88]
Hi, it's me again! First of all, thanks for your awesome package! I love Vue and Meteor, and without you I could not use them together!

I'm currently trying to implement infinite scroll, but every time I change the limit of the subscription and data query, the whole list rerenders completely. For a split second, the list vanishes and then reappears with the increased limit, but the browser is now back at the top and the user has to scroll down again...

For simplicity, look at this example:
```vue
<template>
<div class="list">
  <div class="item" v-for="message in messages" :key="message._id">
    {{ message.text }}
  </div>
  <button v-on:click="loadMore">LOAD MORE</button>
</div>
</template>

<script>
export default {
  data() {
    return {
      limit: 4,
    };
  },

  methods: {
    loadMore: function() {
      this.limit += 2;
      console.log('loadMore', this.limit);
    }
  },

  meteor: {
    subscribe: {
      messages() {
        console.log('subscribe', this.limit);
        return [ this.limit ];
      },
    },
    data: {
      messages: {
        params () {
          return {
            limit: this.limit,
          };
        },
        update ({limit}) {
          console.log('update', limit);
          return Messages.find({}, { limit });
        },
      },
    },
  },
};
</script>
```

So, when the button is clicked, `this.limit` is increased, which causes the subscription to increase its limit, and then the data function as well.

Am I doing something wrong? Is this Vue's fault?

**Comment by cpury** [comment]
Btw, I realized I don't necessarily need to use the limit in the data function, limiting the subscription should be enough. _(This might cause some weird behavior at the bottom of the list if other subscriptions are active, but that's probably fine.)_

Anyway, so I tried removing the dependency on limit from the data function, and that did not solve the issue either :(

**Comment by janat08** [comment]
Did you find solution for this?

**Comment by Akryum** [comment]
Try updating to akryum:vue@1.2.2

**Comment by cpury** [comment]
Hey I just tried with `akryum:vue@1.2.2` and it does work better, but the behavior I described still happens sometimes. Pretty often the scroll position also jumps back to a place somewhere higher up, though not all the way to the top.

**Comment by Akryum** [comment]
I have done [a test](https://github.com/Akryum/vue-meteor-demo/commit/ded042c0d2db47eec9d627c6bc31dae922dbeda1) in the vue-meteor-demo project and didn't have any issue.
