### ISSUE TITLE
CSS should be minified in production

### ISSUE THREAD

**Issue by laosb** [Akryum/vue-meteor#91]
For now, css is inserted as `<style>`s. We should minify it to exclude comments and reduce client bundle size. @Akryum how do you think?

**Comment by mitar** [comment]
@Akryum: This could be closed now, no?

**Comment by Akryum** [comment]
Yup, this only the development behavior.

**Comment by laosb** [comment]
@Akryum Er, I'm still finding unminified <style> tags in my app. Is that intended?

**Comment by Akryum** [comment]
Not in production.

**Comment by laosb** [comment]
But it's exactly in production. https://iw.daoapp.io, for example.

**Comment by lunatolun** [comment]
I have the same issue. JS gets minified but not the CSS. I deploy with [zodern/meteor-up](https://github.com/zodern/meteor-up). It might be an issue from MUP's side.

**Comment by Akryum** [comment]
That's a strange behavior, since the whole HMR system with `<style>` tags is working only if `Meteor.isDevelopment` is true.

**Comment by lunatolun** [comment]
I strongly believe its an issue with MUP because when I do `meteor build --server-only` and check the CSS its minified.
BTW today I tried updating vue, meteor version and all. It messed up all the CSS (it took scoped CSS as global). Should I open a new issue for it?

**Comment by Akryum** [comment]
Did you try resetting the project or just deleting the build files in the
`.local` folder?

**Comment by lunatolun** [comment]
I just tried deleting build files and deployed again and its the same. I think its a problem with MUP. without MUP, build minifies it as it should.

**Comment by Akryum** [comment]
Maybe there is an issue with MUP not setting `NODE_ENV` to `production` or something similar, resulting in `Meteor.isDevelopment` to be `true`.

**Comment by Akryum** [comment]
For now I will close this, as this seems to be related to MUP. Please open an issue in its repository.
